name: Test and Deploy to VM

on:
  push:
    branches:
      - deployed  

jobs:
  test:
    name: Placeholder Test Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code with Submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Placeholder test step
      run: echo "✅Tests haven't been implemented yet. Skipping......"  

  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Code with Submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Ensure full history is available
        
    - name: Update Submodules to Latest
      run: |
        git submodule update --init --recursive
        git submodule foreach git checkout deployed
        git submodule foreach git pull origin deployed

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        echo "SSH key setup complete"
        
    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts || echo "Host key scan failed, continuing..."
        echo "Known hosts updated"

    - name: Test SSH Connection
      run: |
        echo "Testing SSH connection to ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}"
        ssh -i ~/.ssh/deploy_key -o ConnectTimeout=10 -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "echo 'SSH connection successful'"

    - name: Check target directory
      run: |
        echo "Checking target directory structure..."
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "ls -la ${{ secrets.VM_PROJECT_PATH }}"

    - name: Copy Project to VM via rsync (with verbose output)
      run: |
        echo "Starting rsync to ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:${{ secrets.VM_PROJECT_PATH }}"
        # First, backup the .env file on the server
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cd ${{ secrets.VM_PROJECT_PATH }} && cp .env .env.backup 2>/dev/null || echo 'No .env file to backup'"
        
        # Rsync without deleting git directories and important files
        rsync -avz --progress --delete \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='db-backups' \
          --exclude='*.log' \
          --exclude='.env' \
          --exclude='.env.backup' \
          --exclude='routine-scheduler-frontend/.git' \
          --exclude='routine-scheduler-backend/.git' \
          -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:${{ secrets.VM_PROJECT_PATH }}/ || {
            echo "Rsync failed with exit code $?"
            echo "Trying rsync without --delete flag..."
            rsync -avz --progress \
              --exclude='.git' \
              --exclude='node_modules' \
              --exclude='db-backups' \
              --exclude='*.log' \
              --exclude='.env' \
              --exclude='.env.backup' \
              -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
              ./ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:${{ secrets.VM_PROJECT_PATH }}/
          }
        
        # Restore the .env file on the server
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cd ${{ secrets.VM_PROJECT_PATH }} && mv .env.backup .env 2>/dev/null || echo 'No .env backup to restore'"

    - name: Update Submodules on Server
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          cd ${{ secrets.VM_PROJECT_PATH }}
          echo "Updating submodules on server..."
          git submodule update --init --recursive
          cd routine-scheduler-frontend && git checkout deployed && git pull origin deployed
          cd ../routine-scheduler-backend && git checkout deployed && git pull origin deployed
          cd ..
          echo "Submodules updated successfully"
        EOF

    - name: Restart Docker Compose on VM
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          cd ${{ secrets.VM_PROJECT_PATH }}
          docker compose down
          docker compose up -d --build
        EOF
